### ISSUE TITLE
undefined: gocui.Quit undefined: gocui.ModNone

### ISSUE THREAD

**Issue by owllie90** [SumoLogic/sumoshell#12]
i am doing the go get ./... for the installation of sumoshell

But i am encountering the below error:

undefined: gocui.Quit
undefined: gocui.ModNone

Kindly advise

Thanks.

**Comment by rcoh** [comment]
It's caused by a dependency that was upgraded. I have a branch with a fix,
will push soon.

**Comment by owllie90** [comment]
hi, any estimate when? 

Thanks :)

**Comment by rcoh** [comment]
https://github.com/SumoLogic/sumoshell/pull/13

**Comment by rcoh** [comment]
Merged. I have a few more improvements on my list that should come out soon
