### ISSUE TITLE
How to parse stuffs inside double quotes?

### ISSUE THREAD

**Issue by tkt028** [SumoLogic/sumoshell#20]
Hi,
Is it possible to parse stuffs inside a double quote? For this data:

<pre>
Tue Jan 10 2017 21:37:47 GMT+0700 (ICT) - info: 14.175.18.253 - - [10/Jan/2017:14:37:47 +0000] "GET /embed/doSurvey HTTP/1.1" 404 27 "https://abc.me/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
</pre>

I want to count the HTTP code 404 inside, and also the HTTP req URL, I execute

<pre>
$ cat all-logs1.log-RAT  | sumo search "https" | sumo search "info" | sumo parse " - - [*:*:*:* *] "*" * * *" as date, hour, minute, second, sth1, reqUrl, httpCode, sth2, referrer | sumo count httpCode | render-basic

======
0     4        /fonts/fontawesome-webfont.ttf?v=4.5.0
1     2        /fonts/fontawesome-webfont.svg?v=4.5.0
2     229      /embed/doSurvey
3     35       /embed/api/surveys/answerSurvey
</pre>

I did try to escape solution by adding \" or \"" or adding regex option before sumo, but it doesn't work. Thank you very much!

Cheers,
Khon

**Comment by rcoh** [comment]
Did you try `\"`?

**Comment by tkt028** [comment]
I tried it again with "" and it works, but I have to specify explicitly 3 wildcards like this ""* * *"". 
>> SUGGESTION: But it's better if it allows to treat the text inside double quote as a single unit of element for extraction.

<pre>
cat all-logs1.log-RAT  | sumo search "https" | sumo search "info" | sumo parse " - - [*:*:*:* *] ""* * *"" * * * *" as date, hour, minute, second, sth1, httpMethod, reqUrl, protocol, httpCode, size, referral, sth3 | sumo count httpCode date | render
</pre>

**Comment by tkt028** [comment]
Finally, I found that sumoshell doesn't care about double quotes, it just scans for element based on wildcard. As a result, the double quotes is part of the content of the extracted element.
This behavior still fine to me, so I close this ticket.
