### ISSUE TITLE
sumoshell doesn't display all frequency counts

### ISSUE THREAD

**Issue by tkt028** [SumoLogic/sumoshell#21]
Hi,
I use sumoshell to analyze 200MB and it just displayed a short list

<pre>
$ cat all-logs*  | sumo search "https" | sumo search "info" | sumo parse " - - [*:*:*:* *] ""* * *"" * * * *" as date, hour, minute, second, sth1, h
ttpMethod, reqUrl, protocol, httpCode, size, referral, sth3 | sumo count reqUrl date | render
_Id   _count   date          reqUrl
802   306704   13/Jan/2017   /embed/doSurvey
506   306077   12/Jan/2017   /embed/doSurvey
504   280968   12/Jan/2017   /embed/api/checksum
801   274798   13/Jan/2017   /embed/api/checksum
111   273090   11/Jan/2017   /embed/api/checksum
800   269298   13/Jan/2017   /embed/api/surveys/availableSurvey
503   261074   12/Jan/2017   /embed/api/surveys/availableSurvey
112   246314   11/Jan/2017   /embed/doSurvey
113   191381   11/Jan/2017   /embed/api/surveys/availableSurvey
975   122495   14/Jan/2017   /embed/api/checksum
984   83135    14/Jan/2017   /embed/survey/587369ff3adb7605a65f828f
803   56848    13/Jan/2017   /fonts/fontawesome-webfont.woff2?v=4.5.0
505   56121    12/Jan/2017   /fonts/fontawesome-webfont.woff2?v=4.5.0
974   47798    14/Jan/2017   /embed/doSurvey
114   45392    11/Jan/2017   /fonts/fontawesome-webfont.woff2?v=4.5.0
972   44645    14/Jan/2017   /embed/api/surveys/availableSurvey
5     40643    10/Jan/2017   /embed/api/checksum
2     35785    10/Jan/2017   /embed/doSurvey
6     35779    10/Jan/2017   /embed/api/surveys/availableSurvey
</pre>

It seems render command just display a top results only. Is there any option to get the full list of data? Thank you very much!

Cheers,
Khon

**Comment by rcoh** [comment]
There isn't an option, but I'm planning on adding one. Something like `--all`. It won't be auto-updating though, it will print a full dump once the incoming stream is over or ctrl+c is pressed.

**Comment by rcoh** [comment]
I've pushed a fix. New binaries will be pushed after a few more changes.
