### ISSUE TITLE
Does sumo support output to file instead of rendering via curse-based output?

### ISSUE THREAD

**Issue by tkt028** [SumoLogic/sumoshell#25]
Hi,
I want to have a cronjob in server to calculate the statistical report by using sumo. I cannot figure out the option (even Googling) to output restuls to file. Do we have a solution for this? Thank you very much!

Cheers,
Khon

**Comment by rcoh** [comment]
Hi just do `--render-all > myfile` assuming you're on a Unix

**Comment by tkt028** [comment]
Hi rcoh,
Thank you the quick response. It failed with this log:

<pre>
$ cat my-log-file | sumo search | sumo count reqUrl | render --render-all > abc.txt
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x532ba0, 0xc820012160)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.main()
        /home/hajime/go/src/github.com/SumoLogic/sumoshell/render/Render.go:34 +0xbaa
</pre>

Could you please prove more detail? Thank you!
Cheers,
Khon

**Comment by rcoh** [comment]
Hmm you're right I need to fix that. Will do soon.

**Comment by rcoh** [comment]
Fixed in #29, and released in v0.4
