### ISSUE TITLE
Sumo outputs to file is not completed - follow #25

### ISSUE THREAD

**Issue by tkt028** [SumoLogic/sumoshell#30]
Hi rcoh,
Thanks for the fix in #25, but I have to create this issue because it's not completed and you just closed and made new release. I tried your new version and was able to get some output in file, but I expect the file content should have only the final version of the output instead of many duplication data as below.

<pre>
$ cat all-logs.log | sumo search "https" | sumo search "info" | sumo parse " - - [*:*:*:* *] ""* * *"" * * * *" as date, hour, minute, second, sth1, httpMethod, reqUrl, protocol, httpCode, size, referral, sth3 | sumo count httpCode | render --render-all > httpCode-report.txt

$ less httpCode-report.txt
ESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1A_Id   _count   httpCode
2     92042    200
3     27460    304
0     6217     404
4     5125     500
5     1592     302
1     1479     -
7     99       507
6     67       403
8     3        412
ESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1AESC[2KESC[1A_Id   _count   httpCode
2     92777    200
3     27666    304
0     6249     404
4     5126     500
5     1639     302
1     1482     -
7     100      507
6     72       403
8     3        412
</pre>

**Comment by rcoh** [comment]
Weird. Will take a look. Try removing --render-all? It should automatically
default to single output when it's piped to a file

**Comment by rcoh** [comment]
Please try v0.4.1 just released

**Comment by tkt028** [comment]
Thank you @rcoh, it works now!   : D
